'use client';

import React, { useState, useEffect } from 'react';
import Card from '@/components/ui/Card';
import Badge from '@/components/ui/Badge';
import Button from '@/components/ui/Button';
import {
  Bell,
  CheckCircle2,
  AlertTriangle,
  Clock,
  Filter,
  RefreshCw,
  ShieldAlert,
  Info,
  Check,
  CheckCheck,
  Sparkles,
} from 'lucide-react';
import { hospitalApi, subscribeToNotifications } from '@/lib/api';
import { useAuth } from '@/context/AuthContext';

interface NotificationItem {
  id: number;
  title: string;
  message: string;
  priority: 'Critical' | 'High' | 'Medium' | 'Low' | string;
  category: string;
  is_read: boolean;
  created_at: string;
  recipient_id?: string;
}

export default function HospitalNotificationsPage() {
  const { user } = useAuth();
  const [notifications, setNotifications] = useState<NotificationItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [filterPriority, setFilterPriority] = useState<string>('All');
  const [unreadOnly, setUnreadOnly] = useState<boolean>(false);

  const loadNotifications = async () => {
    setLoading(true);
    try {
      const data = (await hospitalApi.getNotifications(unreadOnly)) as NotificationItem[];
      setNotifications(data || []);
    } catch (err) {
      console.error('Failed to load notifications:', err);
      // Fallback empty state if backend has no records yet
      setNotifications([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadNotifications();
  }, [unreadOnly]);

  useEffect(() => {
    if (!user) return;
    const unsub = subscribeToNotifications('hospital', user.uid, () => {
      loadNotifications();
    });
    return () => unsub();
  }, [user]);

  const handleMarkAsRead = async (id: number) => {
    try {
      await hospitalApi.markNotificationRead(id);
      setNotifications((prev) =>
        prev.map((n) => (n.id === id ? { ...n, is_read: true } : n))
      );
    } catch (err) {
      console.error('Failed to mark read:', err);
      // Optimistic UI update
      setNotifications((prev) =>
        prev.map((n) => (n.id === id ? { ...n, is_read: true } : n))
      );
    }
  };

  const handleMarkAllRead = async () => {
    const unread = notifications.filter((n) => !n.is_read);
    for (const item of unread) {
      await handleMarkAsRead(item.id);
    }
  };

  const filteredNotifications = notifications.filter((n) => {
    if (filterPriority !== 'All' && n.priority !== filterPriority) return false;
    return true;
  });

  const getPriorityBadge = (priority: string) => {
    switch (priority) {
      case 'Critical':
        return <Badge variant="critical" dot>Critical</Badge>;
      case 'High':
        return <Badge variant="warning" dot>High Priority</Badge>;
      case 'Medium':
        return <Badge variant="info">Medium</Badge>;
      default:
        return <Badge variant="neutral">Low</Badge>;
    }
  };

  const getCategoryIcon = (priority: string) => {
    switch (priority) {
      case 'Critical':
        return <ShieldAlert className="h-6 w-6 text-rose-600 animate-pulse" />;
      case 'High':
        return <AlertTriangle className="h-6 w-6 text-amber-600" />;
      default:
        return <Info className="h-6 w-6 text-blue-600" />;
    }
  };

  return (
    <div className="space-y-8 animate-fadeIn">
      {/* Header Banner */}
      <div className="relative overflow-hidden rounded-3xl bg-gradient-to-r from-slate-900 via-indigo-950 to-slate-900 p-8 text-white shadow-xl">
        <div className="absolute right-0 top-0 -mt-12 -mr-12 h-64 w-64 rounded-full bg-brand-blue/20 blur-3xl pointer-events-none"></div>
        <div className="relative z-10 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-6">
          <div className="space-y-2">
            <div className="inline-flex items-center gap-2 rounded-full bg-indigo-500/20 px-3 py-1 text-xs font-semibold text-indigo-300 backdrop-blur-md border border-indigo-500/30">
              <Sparkles className="h-3.5 w-3.5 text-indigo-400" /> AI Alert Centre & Notifications
            </div>
            <h1 className="text-3xl font-black tracking-tight text-white">
              Operational Intelligence Feed
            </h1>
            <p className="text-sm text-slate-300 max-w-2xl font-medium">
              Real-time alerts generated by the AI Intelligence Engine regarding medicine stock predictions, bed occupancy spikes, and emergency resource requests.
            </p>
          </div>
          <div className="flex items-center gap-3">
            <Button
              variant="outline"
              size="sm"
              onClick={loadNotifications}
              className="bg-white/10 text-white border-white/20 hover:bg-white/20 backdrop-blur-md"
            >
              <RefreshCw className={`h-4 w-4 mr-2 ${loading ? 'animate-spin' : ''}`} /> Refresh
            </Button>
            <Button
              variant="primary"
              size="sm"
              onClick={handleMarkAllRead}
              className="bg-gradient-to-r from-indigo-500 to-blue-600 hover:from-indigo-600 hover:to-blue-700 text-white shadow-lg shadow-indigo-500/25 border-0"
            >
              <CheckCheck className="h-4 w-4 mr-2" /> Mark All Read
            </Button>
          </div>
        </div>
      </div>

      {/* Filter Bar */}
      <Card padding="sm" className="bg-white/80 backdrop-blur-md border border-slate-200/80 shadow-sm">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-center gap-3 flex-wrap">
            <span className="text-xs font-bold text-slate-500 uppercase tracking-wider flex items-center gap-1.5">
              <Filter className="h-3.5 w-3.5 text-slate-400" /> Priority Filter:
            </span>
            {['All', 'Critical', 'High', 'Medium', 'Low'].map((p) => (
              <button
                key={p}
                onClick={() => setFilterPriority(p)}
                className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all ${
                  filterPriority === p
                    ? 'bg-slate-900 text-white shadow-md shadow-slate-900/10'
                    : 'bg-slate-100 text-slate-600 hover:bg-slate-200/70'
                }`}
              >
                {p}
              </button>
            ))}
          </div>

          <div className="flex items-center gap-3">
            <label className="inline-flex items-center cursor-pointer">
              <input
                type="checkbox"
                checked={unreadOnly}
                onChange={(e) => setUnreadOnly(e.target.checked)}
                className="sr-only peer"
              />
              <div className="relative w-11 h-6 bg-slate-200 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full rtl:peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:start-[2px] after:bg-white after:border-slate-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-indigo-600"></div>
              <span className="ms-3 text-xs font-bold text-slate-700">Unread Only</span>
            </label>
          </div>
        </div>
      </Card>

      {/* Notifications List */}
      <div className="space-y-4">
        {loading ? (
          <Card padding="lg" className="text-center py-16">
            <RefreshCw className="h-8 w-8 text-indigo-500 animate-spin mx-auto mb-3" />
            <h3 className="font-bold text-slate-700">Loading intelligence notifications...</h3>
          </Card>
        ) : filteredNotifications.length === 0 ? (
          <Card padding="lg" className="text-center py-16 bg-gradient-to-b from-white to-slate-50/50">
            <div className="w-16 h-16 rounded-full bg-slate-100 flex items-center justify-center mx-auto mb-4 text-slate-400">
              <Bell className="h-8 w-8" />
            </div>
            <h3 className="text-lg font-bold text-slate-800">All caught up!</h3>
            <p className="text-sm text-slate-500 max-w-md mx-auto mt-1">
              No active operational alerts match your current filter criteria. The AI engine is continuously monitoring district resources.
            </p>
          </Card>
        ) : (
          filteredNotifications.map((item) => (
            <Card
              key={item.id}
              padding="md"
              className={`transition-all duration-200 border-l-4 ${
                !item.is_read
                  ? 'bg-gradient-to-r from-indigo-50/40 via-white to-white border-l-indigo-600 shadow-md ring-1 ring-indigo-500/10'
                  : 'bg-white border-l-slate-200 opacity-80 hover:opacity-100'
              }`}
            >
              <div className="flex items-start justify-between gap-4">
                <div className="flex items-start gap-4">
                  <div
                    className={`p-3 rounded-2xl flex-shrink-0 mt-1 ${
                      item.priority === 'Critical'
                        ? 'bg-rose-50 border border-rose-100'
                        : item.priority === 'High'
                        ? 'bg-amber-50 border border-amber-100'
                        : 'bg-blue-50 border border-blue-100'
                    }`}
                  >
                    {getCategoryIcon(item.priority)}
                  </div>
                  <div className="space-y-1.5">
                    <div className="flex items-center gap-2.5 flex-wrap">
                      <h4 className="text-base font-extrabold text-slate-900 tracking-tight">
                        {item.title}
                      </h4>
                      {getPriorityBadge(item.priority)}
                      {!item.is_read && (
                        <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-black uppercase tracking-wider bg-indigo-600 text-white animate-pulse">
                          New
                        </span>
                      )}
                    </div>
                    <p className="text-sm text-slate-600 font-medium leading-relaxed">
                      {item.message}
                    </p>
                    <div className="flex items-center gap-4 text-xs font-semibold text-slate-400 pt-1">
                      <span className="flex items-center gap-1">
                        <Clock className="h-3.5 w-3.5" />
                        {item.created_at ? new Date(item.created_at).toLocaleString() : 'Just now'}
                      </span>
                      <span className="uppercase tracking-wider text-[10px] bg-slate-100 px-2 py-0.5 rounded text-slate-600 font-bold">
                        {item.category || 'System AI'}
                      </span>
                    </div>
                  </div>
                </div>

                {!item.is_read && (
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => handleMarkAsRead(item.id)}
                    className="flex-shrink-0 text-xs border-slate-200 hover:bg-slate-100 font-bold"
                  >
                    <Check className="h-3.5 w-3.5 mr-1.5 text-emerald-600" /> Acknowledge
                  </Button>
                )}
              </div>
            </Card>
          ))
        )}
      </div>
    </div>
  );
}
